sonar.projectKey=Concord-API_API5-Frontend
sonar.organization=concord-api
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx,src/test/**
sonar.exclusions=src/**/*.test.ts,src/**/*.test.tsx,src/test/**,src/routeTree.gen.ts
sonar.coverage.exclusions=src/main.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
