/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as LimitacoesRouteImport } from './routes/limitacoes'
import { Route as TemaKeyRouteImport } from './routes/tema.$key'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const LimitacoesRoute = LimitacoesRouteImport.update({
  id: '/limitacoes',
  path: '/limitacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const TemaKeyRoute = TemaKeyRouteImport.update({
  id: '/tema/$key',
  path: '/tema/$key',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/limitacoes': typeof LimitacoesRoute
  '/tema/$key': typeof TemaKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/limitacoes': typeof LimitacoesRoute
  '/tema/$key': typeof TemaKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/limitacoes': typeof LimitacoesRoute
  '/tema/$key': typeof TemaKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/busca' | '/limitacoes' | '/tema/$key'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/busca' | '/limitacoes' | '/tema/$key'
  id: '__root__' | '/' | '/busca' | '/limitacoes' | '/tema/$key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuscaRoute: typeof BuscaRoute
  LimitacoesRoute: typeof LimitacoesRoute
  TemaKeyRoute: typeof TemaKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/limitacoes': {
      id: '/limitacoes'
      path: '/limitacoes'
      fullPath: '/limitacoes'
      preLoaderRoute: typeof LimitacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tema/$key': {
      id: '/tema/$key'
      path: '/tema/$key'
      fullPath: '/tema/$key'
      preLoaderRoute: typeof TemaKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuscaRoute: BuscaRoute,
  LimitacoesRoute: LimitacoesRoute,
  TemaKeyRoute: TemaKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
